@Tags(['corpus'])
library;

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:hintpcb/domain/pcb/pcb.dart';
import 'package:hintpcb/kicad/footprint_parser.dart';
import 'package:hintpcb/kicad/sexpr/sexpr_parser.dart';

/// Parses every stock KiCad footprint installed on this machine.
///
/// The same bet as the symbol corpus test, for the same reason: a fixture
/// proves the parser understands the format as documented, and this proves
/// it understands the format as tens of thousands of real files actually
/// write it. Pads with oval drills, layer wildcards, custom shapes and
/// footprints generated by five different tools all live here.
///
/// Skipped automatically where KiCad is not installed. Run explicitly with
/// `flutter test --tags corpus`.
void main() {
  const path = '/usr/share/kicad/footprints';
  final root = Directory(path);

  if (!root.existsSync()) {
    test('KiCad footprint libraries are not installed', () {}, skip: true);
    return;
  }

  final libraries =
      root.listSync().whereType<Directory>().where(
        (d) => d.path.endsWith('.pretty'),
      ).toList()..sort((a, b) => a.path.compareTo(b.path));

  String nicknameOf(Directory library) {
    final base = library.path.split('/').last;
    return base.substring(0, base.length - '.pretty'.length);
  }

  test('every stock footprint parses without error', () {
    expect(libraries, isNotEmpty, reason: 'expected libraries at $path');

    final stopwatch = Stopwatch()..start();
    var footprints = 0;
    var pads = 0;
    var smd = 0;
    var throughHole = 0;
    var graphics = 0;
    final shapes = <PadShape, int>{};
    final failures = <String>[];

    for (final library in libraries) {
      final nickname = nicknameOf(library);
      for (final file in library.listSync().whereType<File>()) {
        if (!file.path.endsWith('.kicad_mod')) continue;
        try {
          final node = SExprParser.parseDocument(file.readAsStringSync());
          final footprint = FootprintParser.parse(node, nickname);

          expect(footprint.name, isNotEmpty, reason: file.path);
          expect(footprint.libraryNickname, nickname, reason: file.path);

          footprints++;
          pads += footprint.pads.length;
          graphics += footprint.graphics.length;
          if (footprint.isSurfaceMount) smd++;
          if (footprint.isThroughHole) throughHole++;
          for (final pad in footprint.pads) {
            shapes[pad.shape] = (shapes[pad.shape] ?? 0) + 1;
          }
        } catch (error) {
          failures.add('${file.path}: $error');
        }
      }
    }

    expect(failures, isEmpty, reason: failures.take(10).join('\n'));
    expect(footprints, greaterThan(10000));
    expect(pads, greaterThan(50000));

    // Every shape the corpus contains must have been recognised as itself.
    // Falling back to `rect` for everything would still "parse", and would
    // draw a board full of squares.
    expect(shapes.keys, containsAll(PadShape.values.toSet()));

    // ignore: avoid_print
    print(
      'footprint corpus: ${libraries.length} libraries, $footprints '
      'footprints ($smd SMD, $throughHole THT), $pads pads, $graphics '
      'graphics in ${stopwatch.elapsedMilliseconds} ms',
    );
  });

  test('pads carry the geometry routing depends on', () {
    // Spot-checked against the files themselves. If these drift, every pad
    // on the board is in the wrong place by the same amount, which is the
    // kind of error that looks fine until it is fabricated.
    final resistor = _load(
      '$path/Resistor_SMD.pretty/R_0805_2012Metric.kicad_mod',
      'Resistor_SMD',
    );
    expect(resistor.padCount, 2);
    expect(resistor.isSurfaceMount, isTrue);

    final pad1 = resistor.pads.firstWhere((p) => p.number == '1');
    expect(pad1.shape, PadShape.roundrect);
    expect(pad1.type, PadType.smd);
    expect(pad1.at.x, closeTo(-0.9125, 1e-9));
    expect(pad1.at.y, closeTo(0, 1e-9));
    expect(pad1.sizeX, closeTo(1.025, 1e-9));
    expect(pad1.sizeY, closeTo(1.4, 1e-9));
    expect(pad1.drill, 0);
    // A surface-mount pad lives on one side only.
    expect(pad1.layers, contains(BoardLayer.frontCopper));
    expect(pad1.layers, isNot(contains(BoardLayer.backCopper)));

    final dip = _load(
      '$path/Package_DIP.pretty/DIP-8_W7.62mm.kicad_mod',
      'Package_DIP',
    );
    expect(dip.padCount, 8);
    expect(dip.isThroughHole, isTrue);

    final hole = dip.pads.firstWhere((p) => p.number == '1');
    expect(hole.type, PadType.thruHole);
    expect(hole.drill, closeTo(0.8, 1e-9));
    // `*.Cu` has to reach both sides, or a through-hole pad cannot be
    // routed to from the back.
    expect(
      hole.layers,
      containsAll([BoardLayer.frontCopper, BoardLayer.backCopper]),
    );
  });

  test('an unplated mounting hole is not offered as a connection', () {
    for (final library in libraries) {
      final nickname = nicknameOf(library);
      for (final file in library.listSync().whereType<File>()) {
        if (!file.path.endsWith('.kicad_mod')) continue;
        final footprint = FootprintParser.parse(
          SExprParser.parseDocument(file.readAsStringSync()),
          nickname,
        );
        for (final pad in footprint.pads) {
          if (pad.type != PadType.npth) continue;
          expect(
            pad.isConnectable,
            isFalse,
            reason: '${footprint.libId} pad ${pad.number}',
          );
        }
      }
    }
  });
}

FootprintDefinition _load(String path, String nickname) => FootprintParser.parse(
  SExprParser.parseDocument(File(path).readAsStringSync()),
  nickname,
);
